=== hulaalol/sda1s3/XSL_applytemplate/memo.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">
    
    <xs:element name="memo">
        <xs:complexType>
            <xs:sequence> 
                <xs:element name="from" type="Person"/> 
                <xs:element name="to" type="Person" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element name="subject" type="xs:string"/>
                <xs:element ref="content"/>
            </xs:sequence>
            <xs:attribute name="date" type="xs:date" use="required"/> 
            <xs:attribute name="priority" type="Priority" use="optional"/>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="Person">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:ID"/>
            </xs:extension>
        </xs:simpleContent>               
    </xs:complexType>
    
    <xs:element name="content">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="para" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
    
    <xs:element name="para">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element ref="link" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="link">
        <xs:complexType mixed="true">
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="linkend" type="xs:IDREF"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="Priority">
        <xs:restriction base="xs:string">
            <xs:enumeration value="low"/>
            <xs:enumeration value="medium"/>
            <xs:enumeration value="high"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== hulaalol/sda1s3/XSL_applytemplate/document.xml
<memo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="memo.xsd"
    date="2014-09-24" priority="high" >
    <from id="gurke">Marcel Hasenbalg</from>
    <to>Robi Renner</to>
    <to id="harrison">Eve Gardener</to>
    <to id="chewbaca">Basti</to>
    <to id="yoda">Herbert</to>
    <to id="luke">Christophe</to>
    <to id="anakin">Gunther</to>
    <to id="padme">Scheschonka</to>
    <subject>Test</subject>
    <content>
        <para>See about XLST</para>
        <para>More stuff emerging! <link linkend="gurke">sender</link>.</para>
    </content>
</memo>

=== hulaalol/sda1s3/XLST/instance.xml
<memo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="memo.xsd"
    date="2014-09-24" priority="high" >
    <from id="goik">Marcel Hasenbalg</from>
    <to>Robi Renner</to>
    <to id="eve">Eve Gardener</to>
    <subject>Test</subject>
    <content>
        <para>See about XLST</para>
        <para>Mre stuff emerging! <link linkend="goik">sender</link>.</para>
    </content>
</memo>
