=== hulaalol/sda1s3/Book2Html/Book1/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
    
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1">
    
    <xs:element name="book">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element ref="chapter" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="title" type="xs:string"/>
    
    <xs:element name="chapter">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element name="para"  type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
        
</xs:schema>

=== hulaalol/sda1s3/Book2Html/Book1/work.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="book.xsd">
    <title>Beginning XSL</title>
    <chapter>
        <title>Basic structure</title>
        <para>An XSLT consists of a stylesheet declaration and a set of templates.</para>
        <para>Do not forget: template elements must not be nested!</para>
    </chapter>
    <chapter>
        <title >Important elements</title>
        <para>Some more text.</para>
        <para>The first chapter explains basic structures.</para>
    </chapter>
</book>
